export enum ProgramEnum {
  'BLEU_0' = 'Ceinture Bleu 0 cap',
  'BLEU_1' = 'Ceinture Bleu 1er cap',
  'BLEU_2' = 'Ceinture Bleu 2ème cap',
  'BLEU_3' = 'Ceinture Bleu 3ème cap',
  'JAUNE_1' = 'Ceinture Noir 1ère dan',
  'JAUNE_2' = 'Ceinture Noir 2ème dan',
  'JAUNE_3' = 'Ceinture Noir 3ème dan',
  'ROUGE_0' = 'Ceinture Noir 4ème dan',
  'ROUGE_1' = 'Ceinture Noir 5ème dan',
  'ROUGE_2' = 'Ceinture Noir 6ème dan',
  'ROUGE_3' = 'Ceinture Noir 7ème dan',
  'ROUGE_4' = 'Ceinture Noir 8ème dan',
  'ROUGE_5' = 'Ceinture Noir 9ème dan',
  'ROUGE_6' = 'Ceinture Noir 10ème dan',
}
