export enum TechnichalEnum {
  /*-------Positions-----------*/
  POSITION_1 = 'Lap tan mot',
  POSITION_2 = 'Lap tan hai',
  POSITION_3 = 'Lien Hoa Tan',
  POSITION_4 = 'Din Tan',
  POSITION_5 = 'Chao Ma Tan',
  POSITION_6 = 'Thai am tan',
  POSITION_7 = 'Toa tan',
  POSITION_8 = 'Doc Hanh Thien Tan',
  POSITION_10 = 'Xa Tan mot',
  POSITION_11 = 'Xa Tan Hai',
  POSITION_12 = 'Ho Tan',
  POSITION_13 = 'Hac Tan',
  POSITION_14 = 'Duong Cung Tan',
  POSITION_15 = 'Quy Tan',
  POSITION_17 = 'Thu Bin Tan',
  POSITION_18 = 'Tu Binh Tan',
  POSITION_19 = 'Hung Tan',
  POSITION_20 = 'Ho Vi Tan',

  /*-------Coups de poing-----------*/
  Coup_de_poing_1 = 'Dam Thang mot',
  Coup_de_poing_2 = 'Dam Thang hai',
  Coup_de_poing_3 = 'Dam Moc',
  Coup_de_poing_4 = 'Dam Moc',
  Coup_de_poing_5 = 'Dam Lao',
  Coup_de_poing_6 = 'Dam Lao',
  Coup_de_poing_7 = 'Dam Thap',
  Coup_de_poing_8 = 'Dam T u do',
  /*-------Coups de pied-----------*/
  Coup_de_pied_1 = 'Da Tahng',
  Coup_de_pied_2 = 'Da Canh',
  Coup_de_pied_4 = 'Da Hat Mot',
  Coup_de_pied_6 = 'Da Hat Hai',
  Coup_de_pied_7 = 'Da',
  Coup_de_pied_8 = 'Da',


 /*-------Techniques de tranchant-----------*/
  Chem_1 = 'Chem  1',
  Chem_2 = 'Chem  2',
  Chem_3 = 'Chem  3',
  Chem_4 = 'Chem  4',
  Chem_5 = 'Chem  5',
  Chem_6 = 'Chem  6',
  Chem_7 = 'Chem  7',
  Chem_8 = 'Chem  8',
   /*-------Techniques de coude-----------*/
   Goi_1 = 'Goi  1',
   Goi_2 = 'Goi  2',
   Goi_3 = 'Goi  3',
   Goi_4 = 'Goi  4',
   Goi_5 = 'Goi  5',
   Goi_6 = 'Goi  6',
   Goi_7 = 'Goi  7',
   Goi_8 = 'Goi  8',
 
  /*-------Techniques de contre-attaque-----------*/
  Phan_Don_1 = 'Dam Tahng Phai',
  Phan_Don_2 = 'Dam Tahng Trai',
  Phan_Don_4 = 'Dam Moc Phai',
  Phan_Don_6 = 'Dam Moc Trai',
  Phan_Don_7 = 'Dam Muc Phai',
  Phan_Don_8 = 'Dam Muc Trai',
  Phan_Don_9 = 'Dam Thap Phai',
  Phan_Don_10 = 'Dam Thap Trai',
  Phan_Don_11 = 'Da Tat Phai',
  Phan_Don_12 = 'Da Tat Trai',
  Phan_Don_13 = 'Da Dap Phai',
  Phan_Don_14 = 'Da Dap Trai',
  /*-------Luttes-----------*/
  Vat_1 = 'Vat 1',
  Vat_2 = 'Vat 2',
  Vat_3 = 'Vat 3',
  Vat_4 = 'Vat 4',
  Vat_5 = 'Vat 5',
  Vat_6 = 'Vat 6',
  Vat_7 = 'Vat 7',
  Vat_8 = 'Vat 8',
  Vat_9 = 'Vat 9',
  Vat_10 = 'Vat 10',
  /*-------Ciseaux-----------*/
  Ciseau_1 = 'Don Chan 1',
  Ciseau_2 = 'Don Chan 2',
  Ciseau_3 = 'Don Chan 3',
  Ciseau_4 = 'Don Chan 4',
  Ciseau_5 = 'Don Chan 5',
  Ciseau_6 = 'Don Chan 6',
  Ciseau_7 = 'Don Chan 7',
  Ciseau_8 = 'Don Chan 8',
  Ciseau_9 = 'Don Chan 9',
  Ciseau_10 = 'Don Chan 10',
  Ciseau_11 = 'Don Chan 11',
  Ciseau_12 = 'Don Chan 12',
  Ciseau_13 = 'Don Chan 13',
  Ciseau_14 = 'Don Chan 14',
  Ciseau_15 = 'Don Chan 15',
  Ciseau_16 = 'Don Chan 16',
  Ciseau_17 = 'Don Chan 17',
  Ciseau_18 = 'Don Chan 18',
  Ciseau_19 = 'Don Chan 19',
  Ciseau_20 = 'Don Chan 20',
  Ciseau_21 = 'Don Chan 21',
  Ciseau_22 = 'Don Chan 22',
  Ciseau_23 = 'Don Chan 23',
  /*-------Song Luyen-----------*/
  Song_Luyen_1 = 'Song Luyen 1',
  Song_Luyen_2 = 'Song Luyen 2',
  Song_Luyen_3 = 'Song Vat 1',
  Song_Luyen_4 = 'Song Vat 2',
  Song_Luyen_5 = 'Song Luyen Dao 1',
  Song_Luyen_6 = 'Song Luyen Dao 2',
  /*-------Clés-----------*/
  Cle_1  = 'Clé 1',
  Cle_2 = 'Clé 2',
  Cle_3 = 'Clé 3',
  Cle_4 = 'Clé 4',
  Cle_5 = 'Clé 5',
  Cle_6 = 'Clé 6',
  Cle_7 = 'Clé 7',
  Cle_8 = 'Clé 8',
  Cle_9 = 'Clé 9',
  Cle_10 = 'Clé 10',
  Cle_11 = 'Clé 11',
  Cle_12 = 'Clé 12',
  Cle_13 = 'Clé 13',
  Cle_14 = 'Clé 14',
  Cle_15 = 'Clé 15',
  Cle_16 = 'Clé 16',
  Cle_17 = 'Clé 17',
  Cle_18 = 'Clé 18',
  Cle_19 = 'Clé 19',
  Cle_20 = 'Clé 20',
  Cle_21 = 'Clé 21',
  Cle_22 = 'Clé 22',
  Cle_23 = 'Clé 23',
  Cle_24 = 'Clé 24',
  Cle_25 = 'Clé 25',
  Cle_26 = 'Clé 26',
  Cle_27 = 'Clé 27',
  Cle_28 = 'Clé 28',
  Cle_29 = 'Clé 29',
  Cle_30 = 'Clé 30',
  Cle_31 = 'Clé 31',
  Cle_32 = 'Clé 32',
  /*-------Roulades-----------*/
  Roulade_1 = 'Lan Lon 1',
  Roulade_2 = 'Lan Lon 2',
  Roulade_3 = 'Lan Lon 3',
  Roulade_4 = 'Lan Lon 4',
  Roulade_5 = 'Lan Lon 5',
  Roulade_6 = 'Lan Lon 6',
  Roulade_7 = 'Lan Lon 7',
  Roulade_8 = 'Lan Lon 8',
  Roulade_9 = 'Lan Lon 9',
  /*-------Endurance-----------*/
  Endurance = 'Endurance'
  
}
